apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - awesome-app-ing-overlay.yml
  - awesome-app-deploy-overlay.yml
namespace: awesome-app-tst
nameSuffix: "-tst"
commonLabels:
  env: tst
