apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - awesome-app-ing-overlay.yml
  - awesome-app-deploy-overlay.yml

namespace: awesome-app-tst

nameSuffix: "-tst"

commonLabels:
  env: tst

images:
  - name: bespinian/awesome-image
    newTag: 1.0.1

configMapGenerator:
  - name: awesome-app-config
    namespace: awesome-app
    behavior: merge
    literals:
      - dbHost=db-tst.bespinian.io
      - appVersion=1.0.1
