apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - awesome-app-ing-overlay.yml
  - awesome-app-deploy-overlay.yml
namespace: awesome-app-dev
nameSuffix: "-dev"
commonLabels:
  env: dev
images:
  - name: bespinian/awesome-image
    newTag: 2.0.0
