apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - awesome-app-ing-overlay.yml
  - awesome-app-deploy-overlay.yml
namespace: awesome-app-dev
nameSuffix: "-dev"
commonLabels:
  env: dev
configMapGenerator:
  - name: awesome-app-config
    namespace: awesome-app
    behavior: merge
    literals:
      - dbHost=db-dev.bespinian.io
      - appVersion=2.0.0
images:
  - name: bespinian/awesome-image
    newTag: 2.0.0
