apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awesome-app-ing
  namespace: awesome-app
  labels:
    app: awesome-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: awesome.bespinian.io
      http:
        paths:
          - path: /.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: awesome-app
                port:
                  number: 80
